export const data = [
  {
    company: "Company A",
    salary: 75000,
    position: "Software Engineer",
    location: "New York",
    jobType: "On-site",
  },
  {
    company: "Company B",
    salary: null,
    position: "Data Analyst",
    location: "San Francisco",
    jobType: "Remote",
  },
  {
    company: "Company C",
    salary: 90000,
    position: "UX Designer",
    location: "Los Angeles",
    jobType: "Hybrid",
  },
  {
    company: "Company D",
    salary: 80000,
    position: "Product Manager",
    location: "Seattle",
    jobType: "On-site",
  },
  {
    company: "Company E",
    salary: 65000,
    position: "Front-end Developer",
    location: "Chicago",
    jobType: "Remote",
  },
  {
    company: "Company F",
    salary: null,
    position: "Marketing Coordinator",
    location: "Miami",
    jobType: "Hybrid",
  },
  {
    company: "Company G",
    salary: 85000,
    position: "Data Scientist",
    location: "Boston",
    jobType: "On-site",
  },
  {
    company: "Company H",
    salary: 70000,
    position: "UI/UX Designer",
    location: "Austin",
    jobType: "Remote",
  },
  {
    company: "Company I",
    salary: 95000,
    position: "DevOps Engineer",
    location: "Denver",
    jobType: "Hybrid",
  },
  {
    company: "Company J",
    salary: null,
    position: "Customer Support Specialist",
    location: "Dallas",
    jobType: "On-site",
  },
];
